### ISSUE TITLE
[BUG] terminate called after throwing an instance of 'nlohmann::detail::parse_error'

### ISSUE THREAD

**Issue by CrashedLife** [Almamu/linux-wallpaperengine#38]
Hey!
When I try to use a background in the wallpaper engine port I'll get an exception.

"terminate called after throwing an instance of 'nlohmann::detail::parse_error'
  what():  [json.exception.parse_error.101] parse error at 1: syntax error - unexpected end of input; expected '[', '{', or a literal
Aborted (core dumped)"

It said that something went wrong while parsing the json but the json is alright.
I've tried over 20 backgrounds and everytime I get this error.

I hope you can help me ^^

**Comment by Almamu** [comment]
Most likely the issue is with the way you're running the background and not the background itself. Can you tell me the ID of one of the backgrounds you're loading? A couple should be enough

**Comment by CrashedLife** [comment]
Sure
https://steamcommunity.com/sharedfiles/filedetails/?id=1980267847
https://steamcommunity.com/sharedfiles/filedetails/?id=1851912143
https://steamcommunity.com/sharedfiles/filedetails/?id=1905804984
https://steamcommunity.com/sharedfiles/filedetails/?id=2065411781

**Comment by Almamu** [comment]
I've tried the four backgrounds you shared and they should load with the latest version of the data-separation branch, although there's no support for features like light and javascript, so those backgrounds won't look as they do on Windows. None of them was complaining about json errors tho, all the things that I fixed were unrelated to that message you reported when opening the issue.

**Comment by CrashedLife** [comment]
I've tried to use the latest data-separation branch but I've still get the errors.
![image](https://user-images.githubusercontent.com/33805688/122257061-ede9b280-cecf-11eb-9cb6-a8abd0f7e4b9.png)

**Comment by Almamu** [comment]
For the sailor moon background you have to use the --pkg switch instead of the --dir because It's a compressed background: https://github.com/Almamu/linux-wallpaperengine/tree/data-separation#541-running-compressed-backgrounds

**Comment by CrashedLife** [comment]
I've tried both methods.

**Comment by Almamu** [comment]
Oh sorry, I did not see the first command in the picture. Is the scene.pkg and project.json in that folder? You should have at least those two files for it to work properly. 
![image](https://user-images.githubusercontent.com/751307/122311284-23af8b00-cf12-11eb-9639-87027e5f18d5.png)

**Comment by Almamu** [comment]
And this should be in the one that is a video:
![image](https://user-images.githubusercontent.com/751307/122311377-55c0ed00-cf12-11eb-91a6-3033822f6205.png)

**Comment by CrashedLife** [comment]
yeah.

![image](https://user-images.githubusercontent.com/33805688/122337101-29bb6100-cf3e-11eb-827a-48b7fd8fd456.png)
![image](https://user-images.githubusercontent.com/33805688/122337221-52435b00-cf3e-11eb-8050-343750cbb85e.png)

somehow test1 work now but it's only a picture and not a live background.

**Comment by Almamu** [comment]
Have you updated your local copy of the project and recompiled it? The error message, Unexpected package header... should be fixed in the last commit of the data-separation branch.

**Comment by CrashedLife** [comment]
Yes, I've deleted the folder at cloned it with
'git clone https://github.com/Almamu/linux-wallpaperengine.git'

But the error still happens.

**Comment by CrashedLife** [comment]
Okay my mistake I've cloned the false branch but I'm get now this error.

![image](https://user-images.githubusercontent.com/33805688/122451951-0083ea80-cfa9-11eb-97dc-d53aaa0de4fa.png)

**Comment by Codename-Texas** [comment]
I can confirm this issue, the same is happening to me. Using the data separation branch replaces the previous error with this:
![image](https://user-images.githubusercontent.com/73334987/122584840-7fd5f480-d063-11eb-9bc2-cc07b943ecbc.png)

**Comment by CrashedLife** [comment]
Btw if it's relevant for debugging I'm using EndeavourOS it's Arch based distro.

**Comment by Almamu** [comment]
> I can confirm this issue, the same is happening to me. Using the data separation branch replaces the previous error with this:
> ![image](https://user-images.githubusercontent.com/73334987/122584840-7fd5f480-d063-11eb-9bc2-cc07b943ecbc.png)
> In case you are wondering, the JSON is valid. Not sure why the error is there. I've tested about 3-4 different wallpapers and the same issue persists.
> (Arch Linux, Nvidia, 5.12.10-zen kernel)

Your issue is different. "unexpected package header" means that the .pkg format is not supported. most of the time it's just a different indicator and nothing else differs, can you link the background you're trying to load so I can add the package version to the list?

> Okay my mistake I've cloned the false branch but I'm get now this error.
> 
> ![image](https://user-images.githubusercontent.com/33805688/122451951-0083ea80-cfa9-11eb-97dc-d53aaa0de4fa.png)

About this one, is that when trying to load one of the backgrounds you linked earlier? I do not get it with any of those on the data-separation branch.

**Comment by CrashedLife** [comment]
> About this one, is that when trying to load one of the backgrounds you linked earlier? I do not get it with any of those on the data-separation branch.

Yeah it's for an example this background.
https://steamcommunity.com/sharedfiles/filedetails/?id=1980267847

**Comment by Almamu** [comment]
> > About this one, is that when trying to load one of the backgrounds you linked earlier? I do not get it with any of those on the data-separation branch.
> 
> Yeah it's for an example this background.
> https://steamcommunity.com/sharedfiles/filedetails/?id=1980267847

Could you try with the latest version? I'm loading that background just fine (the only thing missing being the particles and the clock on top which are features not supported yet).
